### ISSUE TITLE
css not load

### ISSUE THREAD

**Issue by MasoudZeini** [meysampg/yii2-treeview#1]
hi meysam . this extension not work
![untitled](https://user-images.githubusercontent.com/30294418/37563967-7a2847a0-2a84-11e8-944b-625ea511118c.png)

**Comment by meysampg** [comment]
سلام.
این اکستنشن برای ادمین‌ال‌تی‌ای تهیه شده. از تصویر اینطور برمیاد که اونو استفاده نمیکنی، درسته؟ اگه بلی مشخصه که اونطور که در نمونه‌ها اومده تصویر برات نمایش داده نمیشه.

**Comment by MasoudZeini** [comment]
سلام . درسته از ادمین ال تی ای استفاده نمیکنم . من فکر کردم میشه به صورت خام استفاده کرد . در هر صورت ممنون
